version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  # Disable version updates for npm dependencies
  open-pull-requests-limit: 0
  reviewers:
  - yuler
